import Box from '@mui/material/Box'
import Head from 'next/head'
import { useCallback } from 'react'
import Sidebar from '~/components/Sidebar/Sidebar'

import Timer from '~/components/Timer/Timer'
import { api } from '~/utils/api'

export default function Home() {
  const { mutate: createTask } = api.task.create.useMutation()
  const { mutate: finishTask } = api.task.finish.useMutation()
  const { data: currentTask, refetch } = api.task.current.useQuery()

  const handleStartTimer = useCallback(() => {
    createTask({ name: 'test' })
    console.log('created')
    refetch().catch(console.error)
  }, [createTask, refetch])

  const handleStopTimer = useCallback(() => {
    if (currentTask) {
      finishTask(currentTask.id)
    }
  }, [finishTask, currentTask])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box display='flex'>
        <Sidebar />
        <Box
          component='main'
          sx={{ flexGrow: 1, bgcolor: 'background.default', p: 3 }}
        >
          <Timer onStarted={handleStartTimer} onStopped={handleStopTimer} />
        </Box>
      </Box>
    </>
  )
}
