import Box from '@mui/material/Box'
import Head from 'next/head'
import { useCallback } from 'react'
import Sidebar from '~/components/Sidebar/Sidebar'

import Timer from '~/components/Timer/Timer'
import { api } from '~/utils/api'

export default function Home() {
  const { mutate } = api.task.create.useMutation()

  const handleStartTimer = useCallback(() => {
    mutate({ name: 'test' })
  }, [mutate])

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name='description' content='Generated by create-t3-app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Box display='flex'>
        <Sidebar />
        <Box
          component='main'
          sx={{ flexGrow: 1, bgcolor: 'background.default', p: 3 }}
        >
          <Timer onStarted={handleStartTimer} />
        </Box>
      </Box>
    </>
  )
}
